version: '3.4'

services: 
  api:
    build: ./bee_build
    image: ${SERVICE_NAME}
    container_name: ${SERVICE_NAME}
    volumes:
      - gosrc:/go
      - .:/go/src/${API_BASE_DIR}/${API_NAME}
    ports: 
      - "${PORT}:${PORT}"
    environment:
      - PRESUPUESTO_API_MID_HTTP_PORT=${PORT}
      - API_NAME=${API_NAME}
      - RUN_MODE=dev 
      - API_FINANCIERA_URL_CRUD=${API_FINANCIERA_URL_CRUD}
      - API_FINANCIERA_PORT_CRUD=${API_FINANCIERA_PORT_CRUD}
      - API_FINANCIERA_NS_CRUD=${API_FINANCIERA_NS_CRUD}
      - SERVICE_TAGS=traefik.enable=true,traefik.frontend.entryPoints=http,traefik.frontend.rule=Host:${SERVICE_NAME}.localhost   
    command: sh -c 'cd ${API_BASE_DIR}/${API_NAME};go get -v ./...; bee run'
    networks: 
      - back_end

volumes:
  gosrc:
networks: 
  back_end:
    external: true
